---
.gitlab-ci.yml:
  delete: true
.rubocop.yml:
  include_todos: true
appveyor.yml:
  delete: true
Gemfile:
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        version: '~> 1.15.0'
Rakefile:
  changelog_version_tag_pattern: 'v%s'
  changelog_since_tag: '1.2.0'
  requires:
    - 'puppet-strings/tasks'
spec/spec_helper.rb:
  mock_with: ':mocha'
  coverage_report: true
.github/workflows/pr_test.yml:
  unmanaged: false
.github/workflows/nightly.yml:
  unmanaged: false
.github/workflows/spec.yml:
  checks: 'syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop'
  unmanaged: false
.github/workflows/release.yml:
  unmanaged: false
.github/workflows/auto_release.yml:
  unmanaged: false
.travis.yml:
  delete: true
