name 'puppetlabs-lvm'
version '0.1.2'
license 'GPLv2'
summary 'Puppet types and providers to manage LVM'
project_page 'https://github.com/puppetlabs/puppetlabs-lvm'
dependency 'puppetlabs/stdlib', '4.1.x'
